### ISSUE TITLE
await send_command not accepting 'use_textfsm=True'

### ISSUE THREAD

**Issue by walidamer711** [selfuryon/netdev#15]
While trying add use_textfsm=True to send_commad function it raises the below error.

Traceback (most recent call last):
  File "async-ssh.py", line 51, in <module>
    main()
  File "async-ssh.py", line 46, in main
    print(task.result())
  File "async-ssh.py", line 30, in collect_output
    command_result = await connection.send_command(command,use_textfsm=True)
TypeError: send_command() got an unexpected keyword argument 'use_textfsm'
Task exception was never retrieved
future: <Task finished coro=<collect_output() done, defined at async-ssh.py:24> exception=TypeError("send_command() got an unexpected keyword argument 'use_textfsm'",)>
Traceback (most recent call last):
  File "async-ssh.py", line 30, in collect_output
    command_result = await connection.send_command(command,use_textfsm=True)
TypeError: send_command() got an unexpected keyword argument 'use_textfsm'

**Comment by selfuryon** [comment]
Hello, @walidamer711 !
My library doesn't support textfsm, but it's interesting. What do you expect from using this args "use_textfsm=True"?

**Comment by walidamer711** [comment]
Hello,
In reference to the below link, netmiko now support passing this parameter "use_textfsm=True" along with send_command() in order to return structured data parsed with ready textfsm templates created in ntc-templates. So it is all about getting structured data.

https://pynet.twb-tech.com/blog/automation/netmiko-textfsm.html

if you can add this to your library, that will be great.
Thanks

**Comment by selfuryon** [comment]
Oh, it's a great idea! I will realize it in the next release!

**Comment by Ali-aqrabawi** [comment]
@selfuryon i'm interested to work on this, you can assign it to me.

**Comment by selfuryon** [comment]
Related PR #33
