### ISSUE TITLE
device TimeoutError

### ISSUE THREAD

**Issue by ixjx** [selfuryon/netdev#45]
Hello,
here is the logs:
```
INFO:netdev:Host 192.168.47.6: Trying to connect to the device
INFO:netdev:Host 192.168.47.6: Establishing connection to port 22
INFO:asyncssh:Opening SSH connection to 192.168.47.6, port 22
INFO:asyncssh:[conn=0] Connection to 192.168.47.6, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: 192.168.175.160, port 28247
INFO:asyncssh:[conn=0] Beginning auth for user xxxx
INFO:asyncssh:[conn=0] Auth for user xxxx succeeded
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
INFO:asyncssh:[conn=0, chan=0]   Interactive shell requested
INFO:netdev:Host 192.168.47.6: Connection is established
INFO:netdev:Host 192.168.47.6: Reading until pattern
DEBUG:netdev:Host 192.168.47.6: Reading pattern: \>|\]
DEBUG:netdev:Host 192.168.47.6: Reading pattern '\>|\]' was found: "\r\n*************************************************************************\r\n*                         Copyright (C) 2007-2017                       *\r\n*                     Huawei Technologies Co., Ltd.                     *\r\n*                           All rights reserved.                        *\r\n*               Without the owner's prior written consent,              *\r\n*        no decompiling or reverse-engineering shall be allowed.        *\r\n*************************************************************************\r\n\r\n\r\nInfo: The max number of VTY users is 10, and the number\r\n      of current VTY users on line is 3.\r\n      The current login time is 2020-09-13 12:16:56+00:00.\r\nHRP_M<WLWZW-ST-B31-E13-E8000E-C01>"
DEBUG:netdev:Host 192.168.47.6: Establish Connection Output: "\r\n*************************************************************************\r\n*                         Copyright (C) 2007-2017                       *\r\n*                     Huawei Technologies Co., Ltd.                     *\r\n*                           All rights reserved.                        *\r\n*               Without the owner's prior written consent,              *\r\n*        no decompiling or reverse-engineering shall be allowed.        *\r\n*************************************************************************\r\n\r\n\r\nInfo: The max number of VTY users is 10, and the number\r\n      of current VTY users on line is 3.\r\n      The current login time is 2020-09-13 12:16:56+00:00.\r\nHRP_M<WLWZW-ST-B31-E13-E8000E-C01>"
INFO:netdev:Host 192.168.47.6: Setting base prompt
INFO:netdev:Host 192.168.47.6: Finding prompt
INFO:netdev:Host 192.168.47.6: Reading until pattern
DEBUG:netdev:Host 192.168.47.6: Reading pattern: \>|\]
DEBUG:netdev:Host 192.168.47.6: Reading pattern '\>|\]' was found: '\r\nHRP_M<WLWZW-ST-B31-E13-E8000E-C01>'
DEBUG:netdev:Host 192.168.47.6: Found Prompt: 'HRP_M<WLWZW-ST-B31-E13-E8000E-C01>'
DEBUG:netdev:Host 192.168.47.6: Base Prompt: RP_M<WLWZW-ST-B31-E13-E8000E-C01
DEBUG:netdev:Host 192.168.47.6: Base Pattern: [\<|\[]RP_M\<WLWZW\-S[\-\w]*[\>|\]]
INFO:netdev:Host 192.168.47.6: Trying to disable paging
DEBUG:netdev:Host 192.168.47.6: Disable paging command: 'screen-length disable\n'
INFO:netdev:Host 192.168.47.6: Reading until pattern
DEBUG:netdev:Host 192.168.47.6: Reading pattern: [\<|\[]RP_M\<WLWZW\-S[\-\w]*[\>|\]]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<task() done, defined at yibu.py:5> exception=TimeoutError('Host 192.168.47.6 Timeout Error',)>
Traceback (most recent call last):
  File "/root/cli/dev/lib/python3.6/site-packages/netdev/vendors/base.py", line 359, in _read_until_pattern
    output += await asyncio.wait_for(fut, self._timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

I think that the problem might be  my hostname begins with "HRP_M" befor "<" , because of  the  HRP hot standby. I just don`t know how to fix it

**Comment by ixjx** [comment]
fixed
